SPLIT_FRACTION = 0.67
LOOK_BACK = 12
EPOCH_SIZE = 5
BATCH_SIZE = 1

YEARS_INPUT = [2017, 2018, 2019, 2020]

FILE_NAME_LSTM_MODEL = '../dataset/NYISO/lstm_pred.h5'
NYISO_LBMP_COL_NAME = 'LBMP ($/MWHr)'
FILENAME_PREPARED_DATASET = 'dataset.csv'